PM / OPP: Fix build when CONFIG_PM_OPP is not set
Commit b25f2f296b9c760f3ac6f441911934fb90a26e3c [formerly 03ca370fbf7b76d6d002380dbdc2cdc2319f9c80] (PM / OPP: Add
OPP availability change notifier) does not compile if CONFIG_PM_OPP
is not set:

arch/arm/plat-omap/omap-pm-noop.o: In function `opp_get_notifier':
include/linux/opp.h:103: multiple definition of `opp_get_notifier'
include/linux/opp.h:103: first defined here

Also fix incorrect comment.

Signed-off-by: Tony Lindgren <tony@atomide.com>
Signed-off-by: Rafael J. Wysocki <rjw@sisk.pl>

Former-commit-id: a96d69d1b02c4a526bd8c07e0cb10c129025c88c