bridge: Fix build of ipv6 multicast code.
Based upon a report from Stephen Rothwell:

--------------------
net/bridge/br_multicast.c: In function 'br_ip6_multicast_alloc_query':
net/bridge/br_multicast.c:469: error: implicit declaration of function 'csum_ipv6_magic'

Introduced by commit ba5c6a01bf383be27462c8bd3ab9557407ded833 [formerly 08b202b6726459626c73ecfa08fcdc8c3efc76c2] ("bridge
br_multicast: IPv6 MLD support") from the net tree.

csum_ipv6_magic is declared in net/ip6_checksum.h ...
--------------------

Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: d4c4f07df16c767b8efbc44e7cdf795fac326b33