SLUB: Fix per-cpu merge conflict
The slab tree adds a percpu variable usage case (commit
8fdebd1510ff31c27fbc1f817a110291bc69484b [formerly 9dfc6e68bfe6ee452efb1a4e9ca26a9007f2b864] "SLUB: Use this_cpu operations in
slub"), but the percpu tree removes the prefixing of percpu variables (commit
06d74d1601720739567c6468b1d71165764ce338 [formerly dd17c8f72993f9461e9c19250e3f155d6d99df22] "percpu: remove per_cpu__ prefix"),
thus causing the following compilation error:

    CC      mm/slub.o
  mm/slub.c: In function ‘alloc_kmem_cache_cpus’:
  mm/slub.c:2078: error: implicit declaration of function ‘per_cpu_var’
  mm/slub.c:2078: warning: assignment makes pointer from integer without a cast
  make[1]: *** [mm/slub.o] Error 1

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>

Former-commit-id: 1154fab73ccbab010cfaa272b6987c624cfd63c6