audio: mrfld: add aware DAI
BZ: 86953

AWARE needs a separated device to be opened at 8K or 16K. The AWARE task has a
separate task ID which needs to be passed to the firmware. When an AWARE stream
is running, it captures data from the codec and doesn't transfer it to the DDR.
So period elapsed are not expected for this stream. Thus the userspace is
expected to send calls only upto PREPARE.

Modified the AWARE DAI to use the codec Headset DAI. The task ID is queried from
the stream map and passed to the SST driver. The task ID is then stored in the
stream context.

Also removed multiple definitions of dump_bytes() and added a helper for it.
Fixed a bug in GET_PARAMS implementation where the data read was wrongly typecast
and not copied back properly.

Change-Id: I59e4bdafaa51a49dcbe4d20038fdc61ff1ece74f
Signed-off-by: Omair Mohammed Abdullah <omair.m.abdullah@linux.intel.com>
Reviewed-on: http://android.intel.com:8080/83633
Reviewed-by: Abdullah, Omair M <omair.m.abdullah@intel.com>
Reviewed-by: Nilofer, Samreen <samreen.nilofer@intel.com>
Reviewed-by: Prusty, Subhransu S <subhransu.s.prusty@intel.com>
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Reviewed-by: Vinnakota, Lakshmi N <lakshmi.n.vinnakota@intel.com>
Tested-by: Gupta, ArvindX K <arvindx.k.gupta@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

Former-commit-id: 6dd160aaf1d4e7d132827799cc36435af1699a32