console: Fix compilation regression
A regression of building without CONFIG_HW_CONSOLE was introduced with
commit 334bb1a48cf5d72018dc97cc1bccfbb2bd012097 [formerly b45cfba4e9005d64d419718e7ff7f7cab44c1994] (vt,console,kdb:
implement atomic console enter/leave functions).

ERROR: "con_debug_enter" [drivers/serial/kgdboc.ko] undefined!
ERROR: "vc_cons" [drivers/serial/kgdboc.ko] undefined!
ERROR: "fg_console" [drivers/serial/kgdboc.ko] undefined!
ERROR: "con_debug_leave" [drivers/serial/kgdboc.ko] undefined!

When there is no HW console the con_debug_enter and con_debug_leave
functions should have no code.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
CC: Jesse Barnes <jbarnes@virtuousgeek.org>
Reported-by: Randy Dunlap <randy.dunlap@oracle.com>

Former-commit-id: 9261ec1a8d7b17e2540bef7cad3470870d13b61e