Revert "[media] siano: apply debug flag to module level"
This reverts commit 790a6384e84554cd37dbe6e1b6e7e4f73ea740ad [formerly ea3709435c7f2da8852c3d676874cd727253fc60].

As reported by Stephen Rothwell:

After merging the v4l-dvb tree, today's linux-next build (x86_64
allmodconfig) failed like this:

ERROR: "sms_dbg" [drivers/media/dvb/siano/smsusb.ko] undefined!
ERROR: "sms_dbg" [drivers/media/dvb/siano/smsdvb.ko] undefined!

Caused by commit 790a6384e845 [formerly ea3709435c7f] ("[media] siano: apply debug flag to module
level").

Relevant config:
CONFIG_SMS_SIANO_MDTV=m
CONFIG_SMS_USB_DRV=m
CONFIG_SMS_SDIO_DRV=m

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: 9e83b3e434f29d71f923035a6001870d185581ec