ARM: PXA: fix lubbock PCMCIA driver build error
Fix:

ERROR: "pxa2xx_configure_sockets" [drivers/pcmcia/pxa2xx_lubbock_cs.ko] undefined!

by exporting the required function.

Acked-by: Eric Miao <eric.y.miao@gmail.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Former-commit-id: d5240dfd3c80ad2fd17b25ca38d199ab1262ab6e