sparc: Fix build with DEBUG_PAGEALLOC enabled.
[ Upstream commit 79d1451068980c026712df3c5cf37a39ca1330b5 [formerly 0785a8e87be0202744d8681363aecbd4ffbb5f5a] ]

arch/sparc/mm/init_64.c:1622:22: error: unused variable '__swapper_4m_tsb_phys_patch_end' [-Werror=unused-variable]
arch/sparc/mm/init_64.c:1621:22: error: unused variable '__swapper_4m_tsb_phys_patch' [-Werror=unused-variable]

Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: feeb796dfb00a08971120bcc8e71bcaf6a9bf150