hwmon: (s3c-hwmon) Fix build error
The previous patch, commit b6d93bc8f0ea274652e1bda6ebe3a921df74ca92 [formerly be4c23c93c4828d36ac9e1a88410618a61676426] was
from the wrong tree and thus broke the current build which had the
channel configuration name changed.

Fix the following build errors:

drivers/hwmon/s3c-hwmon.c: In function 's3c_hwmon_probe':
drivers/hwmon/s3c-hwmon.c:326: warning: initialization from incompatible pointer type
drivers/hwmon/s3c-hwmon.c:331: error: dereferencing pointer to incomplete type
drivers/hwmon/s3c-hwmon.c:336: error: dereferencing pointer to incomplete type

Signed-off-by: Ben Dooks <ben-linux@fluff.org>
Signed-off-by: Jean Delvare <khali@linux-fr.org>

Former-commit-id: 6d905e67cfd84b42c2171e252a3a0aca269da9f8