[S390] system.h: Fix compile error for 1 and 2 byte cmpxchg
commit 5b204fc19ff408bf67a010306d0fcef375a85f8d [formerly 024914477e15ef8b17f271ec47f1bb8a589f0806] "memcg: move charges of anonymous
swap" revealed that the 1 byte and 2 byte cmpxchg is currently broken:

arch/s390/include/asm/system.h: Assembler messages:
arch/s390/include/asm/system.h:241: Error: junk at end of line: `(%r5)'
make[1]: *** [mm/page_cgroup.o] Error 1
make[1]: *** Waiting for unfinished jobs....

It turned out that commit c28cb74666362d9b6752f77642d044bba9352acb [formerly 987bcdacb18a3adc2a48d85c9b005069c2f4dd7b] ([S390] use
inline assembly contraints available with gcc 3.3.3) broke the inline assembly.
The or operands are now in constraint 3 and 4 instead of 2 and 3.

Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>
Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

Former-commit-id: 1bff779285f89cd0b62955c20cca70ada4074236