mtd: ndfc: fix typo in structure dereference
In commit 73f3d7933f2f1e317f14157a6fcaeaa24be6fd04 [formerly 9d7948c50055e74b693ce9e99a709b2e5bbc1942] (mtd: ndfc: use
ofpart through generic parsing) we dereference a non pointer type
causing the following compiler error:
drivers/mtd/nand/ndfc.c: In function 'ndfc_chip_init':
drivers/mtd/nand/ndfc.c:191: error: invalid type argument of '->' (have 'struct mtd_part_parser_data')

Fix that.

Signed-off-by: Tony Breeds <tony@bakeyournoodle.com>
Acked-by: Dmitry Eremin-Solenikov <dbaryshkov@gmail.com>
Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>

Former-commit-id: 629be5f275ddf0791614f8cbdafc11bde4247850