UBI: fix error message and compilation warnings
Fix the followong compilation warnings introduced by commit
31ef5fb81c0e70c77713d7feaf874d425a287ac7 [formerly 095751a6e0838a712393a74eb0b7b6559dbdbe81]:

drivers/mtd/ubi/scan.c: In function 'check_what_we_have':
drivers/mtd/ubi/scan.c:960: warning: passing argument 1 of 'get_random_bytes' discards qualifiers from pointer target type

Fix the following compilation warnings introduced by commit
8e7f3dd0f8976b0d2a9fc5fb41f898968e2bdf8d [formerly 1a49af2ca019dcb4614c32f832bbcb814b61409c]:

drivers/mtd/ubi/io.c: In function 'ubi_io_read':
drivers/mtd/ubi/io.c:153: warning: initialization makes integer from pointer without a cast
drivers/mtd/ubi/io.c:170: warning: format '%s' expects type 'char *', but argument 5 has type 'int'
drivers/mtd/ubi/io.c:177: warning: format '%zd' expects type 'signed size_t', but argument 7 has type 'int'
drivers/mtd/ubi/io.c:177: warning: too many arguments for format

Also, amend the ECC error code string and add brackets and whitespace
there - this should make the message readable.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Artem Bityutskiy <Artem.Bityutskiy@nokia.com>

Former-commit-id: f5d5b1f8c12a7637ee1145f2f00358eb375edb54