staging: fix rts5139 depends & build
RTS5139 should depend on USB, not USB_SUPPORT, to fix build
errors.
USB_SUPPORT can be enabled for gadget-only support
or when PCI is not enabled.

ERROR: "usb_reset_endpoint" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_kill_urb" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_deregister_dev" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_unlink_urb" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_deregister" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_register_dev" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_free_coherent" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_submit_urb" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_sg_cancel" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_find_interface" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_sg_init" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_register_driver" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_alloc_coherent" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_free_urb" [drivers/staging/rts5139/rts5139.ko] undefined!
ERROR: "usb_alloc_urb" [drivers/staging/rts5139/rts5139.ko] undefined!

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Cc: Edwin Rong <edwin_rong@realsil.com.cn>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: b9c4decbd9530b0c4c6dc4ad0626af628b79cd53