Staging: pohmelfs: fix spaces and TAB coding style issue in crypto.c
This is a patch to the crypto.c file that fixed up a TAB and spaces
Errors found by the checkpatch.pl tools, like
	ERROR: switch and case should be at the same indent
and
	spaces required around that '=' (ctx:VxV)

Signed-off-by: Ruslan Pisarev <ruslan@rpisarev.org.ua>
Acked-by: Evgeniy Polyakov <zbr@ioremap.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: e3f052f2b84f66fcaa9b9149e1e0b4930d78c307