m68knommu: fix broken use of BUAD_TABLE_SIZE in 68328serial driver
Commit 821ffe8632c388df93607243eaace281e68b045c [formerly 8b505ca8e2600eb9e7dd2d6b2682a81717671374] ("serial: 68328serial.c:
remove BAUD_TABLE_SIZE macro") misses one use of BAUD_TABLE_SIZE. So the
resulting 68328serial.c does not compile:

drivers/serial/68328serial.c: In function ‘m68328_console_setup’:
drivers/serial/68328serial.c:1439: error: ‘BAUD_TABLE_SIZE’ undeclared (first use in this function)
drivers/serial/68328serial.c:1439: error: (Each undeclared identifier is reported only once
drivers/serial/68328serial.c:1439: error: for each function it appears in.)

Fix that last use of it.

Signed-off-by: Greg Ungerer <gerg@uclinux.org>
Cc: <stable@kernel.org>

Former-commit-id: 9fcce0baea6628af935b1b485d6606a5a377a052