mfd: Fix Arizona Kconfig entry
The core and irq Arizona parts should be boolean as they depend on non
exported symbols.

This fixes the following build errors:

ERROR: "wm5102_aod" [drivers/mfd/arizona-irq.ko] undefined!
ERROR: "wm5102_irq" [drivers/mfd/arizona-irq.ko] undefined!
ERROR: "irq_set_chip_and_handler_name" [drivers/mfd/arizona-irq.ko]  undefined!
ERROR: "wm5102_patch" [drivers/mfd/arizona-core.ko] undefined!
ERROR: "arizona_irq_init" [drivers/mfd/arizona-core.ko] undefined!
ERROR: "arizona_irq_exit" [drivers/mfd/arizona-core.ko] undefined!

Change-Id: Idad122cb4535c4cc30ef6dce84fdf76aacaf5d8d
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
Signed-off-by: Dimitris Papastamos <dp@opensource.wolfsonmicro.com>

Former-commit-id: 5ab9ffdf5e44cc9f7a574d314fea4e88f06b497f