m68k/hp300: Export hp300_ledstate
The accidental loss of CONFIG_DIO in commit
5af9ff9345c3d97e13231b5db9a714ecb7dd252b [formerly 0e152d80507b75c00aac60f2ffc586360687cd52] ("m68k: reorganize Kconfig options
to improve mmu/non-mmu selections") exposed a missing symbol export in
m68k allmodconfig.  If CONFIG_HP300=y but CONFIG_HPLANCE (which is bool,
and depends on CONFIG_DIO) is not set, and CONFIG_MVME147=y and
CONFIG_MVME147_NET=m, 7990.c is compiled as a module, giving:

ERROR: "ledstate" [drivers/net/ethernet/amd/7990.ko] undefined!

Add the missing export, and rename ledstate to hp300_ledstate while we're
at it, as it's a too generic name.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>

Former-commit-id: f808b8650788f78bc1e5e693712e7d7603ab26bc