V4L/DVB (11111): dvb_dummy_fe: Fix compilation breakage
As reported by Randy Dunlap <randy.dunlap@oracle.com>:
ERROR: "dvb_dummy_fe_ofdm_attach" [drivers/media/video/cx231xx/cx231xx-dvb.ko] undefined!

This happens since cx231xx DVB part still misses the frontend modules.
So, the dummy frontend were used for development. The proper fix is to
implement the DVB modules there, as they will be required.

While this won't happen, lets allow the compilation with or without the
dummy FE testing module.

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: dcd241c384357e5c146299d45d2ee2f4ad439723