omap: Stalker board: switch over to gpio_set_debounce
Commit fd4376f2ed83 [formerly 48feb337475a] arm: omap: switch over to gpio_set_debounce caused
"undefined reference to omap_set_gpio_debounce" build error.

The fix is to use the generic gpiolib function.

Cc: Felipe Balbi <felipe.balbi@nokia.com>
Cc: Kevin Hilman <khilman@deeprootsystems.com>
Signed-off-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>

Former-commit-id: 99716b662ba527ea66172ba215da8a9d0e567c3e