ARM: CSR: PM: fix build error due to undeclared 'THIS_MODULE'
In the new kernel, we will get the following compile error:
arch/arm/mach-prima2/pm.c:141: error: 'THIS_MODULE' undeclared
here (not in a function)
so include module.h head file explicitly

Signed-off-by: Barry Song <baohua.song@csr.com>

Former-commit-id: b2dcb8723eb61d00c40d526702d08f6d805f5f01