ARM: bcmring: fix build failure in mach-bcmring/arch.c
Upstream commit dfe12c5efb96c87ad204d248af6153a02a6570d7 [formerly d1fce9c115eeb93e01c01732dfe9a86cf76009cf]

   "ARM: restart: bcmring: use new restart hook"

breaks building of this platform, since what used to be the
last field of the MACHINE_START/END block didn't have a
trailing comma.  Once another field was added below, we get:

arch/arm/mach-bcmring/arch.c:198: error: request for member 'restart' in something not a structure or union

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Acked-by: Jiandong Zheng <jdzheng@broadcom.com>
Signed-off-by: Olof Johansson <olof@lixom.net>

Former-commit-id: ca43784daa7a400407d851799ac69d3de2b2ab4e