benet: fix build error on 32bit arch
Error comes from commit e8925185578357b0a53 [formerly ac124ff973e27802797]
(be2net: cleanup and refactor stats code)

ERROR: "__udivdi3" [drivers/net/benet/be2net.ko] undefined!

Signed-off-by: Eric Dumazet <eric.dumazet@gmail.com>
CC: Sathya Perla <sathya.perla@emulex.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 68c3e5a7b91513010d2536e4bcd7bdd54d0e6acf