hwmon: remove () used with return
fix checkpatch ERROR:
return is not a function, parentheses are not required

Signed-off-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>
Signed-off-by: Guenter Roeck <guenter.roeck@ericsson.com>

Former-commit-id: 7fe83ad877321f44c8141b8334bd2f6614deb739