usb: musb: omap2430: fix build failure
Fix build failure introduced by commit
6703cdac70400d3f07dfe60042db1bbe5d92649c [formerly 7acc6197b76edd0b932a7cbcc6cfad0a8a87f026] (usb: musb: Idle path retention
and offmode support for OMAP3) when building without gadget
support.

  CC      drivers/usb/musb/omap2430.o
drivers/usb/musb/omap2430.c: In function ‘musb_otg_notifications’:
drivers/usb/musb/omap2430.c:262: error: ‘struct musb’ has no member named ‘gadget_driver’

Signed-off-by: Johan Hovold <jhovold@gmail.com>
Cc: Felipe Balbi <balbi@ti.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: 36a52c009a39049893c9a3a4091f8f8f48585f47