Staging: solo: depends on SND
Fix 56 undefined references to snd_*() functions. First 5 are:

drivers/built-in.o: In function `solo_g723_exit':
(.text+0xa4a4aa): undefined reference to `snd_card_free'
drivers/built-in.o: In function `solo_snd_pcm_init':
solo6010-g723.c:(.text+0xa4a677): undefined reference to `snd_pcm_new'
solo6010-g723.c:(.text+0xa4a6b1): undefined reference to `snd_pcm_set_ops'
solo6010-g723.c:(.text+0xa4a74d): undefined reference to `snd_pcm_lib_preallocate_pages_for_all'
drivers/built-in.o: In function `solo_g723_init':
(.text+0xa4a7f6): undefined reference to `snd_card_create'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Ben Collins <bcollins@bluecherry.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: 4d8152be1804c21ff1698f62a788679664363ed0