[media] DocBook: Add rules to auto-generate some media docbook
Auto-generate the videodev2.h.xml,frontend.h.xml and the indexes.

Some logic at the Makefile helps us to identify when a symbol is missing,
like for example:

Error: no ID for constraint linkend: V4L2-PIX-FMT-JPGL.

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: 04893043ae9ea8aa82b712491ed25ba6c4ffbca3