ARM: S5P: Fix export.h inclusion
Commit 0c8ee0978237 [formerly 32aaeffbd4a7] ("Merge branch 'modsplit-Oct31 2011'...")
breaks build like following and this fixes it to add inclusion
<linux/export.h>.

arch/arm/plat-s5p/sysmmu.c:302: error: 'THIS_MODULE' undeclared here (not in a function)

Signed-off-by: Kukjin Kim <kgene.kim@samsung.com>

Former-commit-id: 12b248eba4fd189216cad14b7dd1cfdacdf90cdf