x86: Fix user return notifier put_cpu_var() invocation
Today's linux-next build (x86_64 allmodconfig) failed like this:

  kernel/user-return-notifier.c: In function
  'fire_user_return_notifiers': kernel/user-return-notifier.c:45:
  error: expected expression before ')' token

Introduced by commit 1f13f620a6a8adcb8fe42a6563fdb011de2610d5 [formerly 7c68af6e32c73992bad24107311f3433c89016e2]
("core, x86: Add user return notifiers") from the tip and kvm trees
but revealed by commit 2da8a97a43aab906ed30a00124469d7bfa40c7cd [formerly e0fdb0e050eae331046385643618f12452aa7e73]
("percpu: add __percpu for sparse") from the percpu tree.

Before that percpu tree commit, "put_cpu_var()" would compile
without error (even though it really needs a parameter).

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Avi Kivity <avi@redhat.com>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Tejun Heo <tj@kernel.org>
Cc: Rusty Russell <rusty@rustcorp.com.au>
Cc: Christoph Lameter <cl@linux-foundation.org>
LKML-Reference: <20091102161722.eea4358d.sfr@canb.auug.org.au>
Signed-off-by: Ingo Molnar <mingo@elte.hu>

Former-commit-id: 3c912b6edaac56cb451e7571c95c15cbb6bd0c81