[IA64] Fix build breakage
In commit 8a038ec6abdcfd844662a3a8f5b2acee39f171d1 [formerly 0ac0c0d0f837c499afd02a802f9cf52d3027fa3b]
cpusets: randomize node rotor used in cpuset_mem_spread_node()

Jack Steiner fixed a problem with too many small tasks being
assigned to node 0. Copy his code to ia64 to avoid build error.

    arch/ia64/kernel/smpboot.c:641: error: ‘cpu_to_node_map’ undeclared (first use in this function)

In commit fa101d86f6e46e8195f8bf13e3531dd13ec915bc [formerly 3bccd996276b108c138e8176793a26ecef54d573]
numa: ia64: use generic percpu var numa_node_id() implementation

Lee Schermerhorn added some set_numa_node() calls - but these
only work on CONFIG_NUMA=y configurations. Surround the calls
with #ifdef CONFIG_NUMA

Signed-off-by: Tony Luck <tony.luck@intel.com>

Former-commit-id: 4ec37de89d8c758ee8115e0e64b3f994910789ee