PCMCIA: fix pxa2xx_lubbock modular build error
ERROR: "pxa2xx_drv_pcmcia_ops" [drivers/pcmcia/pxa2xx_lubbock_cs.ko] undefined!
ERROR: "pxa2xx_drv_pcmcia_add_one" [drivers/pcmcia/pxa2xx_lubbock_cs.ko] undefined!

We also remove __pxa2xx_drv_pcmcia_probe and its export, since this is
no longer required.

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Former-commit-id: d0d26c33b63c7ec10c3fdf9c7ce0aa035f0b3200