nfsd: return success for non-NFS4 nfs4_state_start
Today's linux-next build (sparc64_defconfig) failed like this:

In file included from arch/sparc/kernel/sys_sparc32.c:32:
include/linux/nfsd/nfsd.h: In function 'nfs4_state_start':
include/linux/nfsd/nfsd.h:177: error: no return statement in function returning non-void

Caused by commit 1f593749fa43b666ff94e1bc2c85011ec0392f9c [formerly 29ab23cc5d351658d01a4327d55e9106a73fd04f] ("nfsd4: allow
nfs4 state startup to fail").  Please, if you add code that depends on a
CONFIG option, build with that option enabled and disabled.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: J. Bruce Fields <bfields@citi.umich.edu>

Former-commit-id: c0826574ddc0df486ecfc2d655e08904c6513209