[IA64] fix build error - arch/ia64/kernel/perfmon.c
arch/ia64/kernel/perfmon.c:621: error: duplicate 'static'

Introduced by commit 361d51dc779b670e49cbc973a34f72528d3b1d23 [formerly c74a1cbb3cac348f276fabc381758f5b0b4713b2]

    pass default dentry_operations to mount_pseudo()

Signed-off-by: Tony Luck <tony.luck@intel.com>

Former-commit-id: 09579770dcb8769f4f61046dcd01cc758cfa6d91