ARM: OMAP2/3: PRM: fix missing plat/irqs.h build breakage
Commit eb37b6933ab6765de4a00d222d311523ff2a4221 [formerly 22f51371f8c35869ed850f46aa76b6cc2b502110] ("ARM: OMAP3: pm: use
prcm chain handler") breaks the build on a 2420-only config, due to
a missing include for plat/irqs.h:

  CC      arch/arm/mach-omap2/prm2xxx_3xxx.o
arch/arm/mach-omap2/prm2xxx_3xxx.c:41:11: error: 'INT_34XX_PRCM_MPU_IRQ' undeclared here (not in a function)

Fix by explicitly including it.

Signed-off-by: Paul Walmsley <paul@pwsan.com>
Cc: Tero Kristo <t-kristo@ti.com>
Cc: Kevin Hilman <khilman@ti.com>

Former-commit-id: d19e8f2e44a34b2a461f67ce9d0cb5bd43197c1e