kmemtrace, security: fix linux/key.h header file dependencies
Impact: cleanup

We want to remove percpu.h from rcupdate.h (for upcoming kmemtrace
changes), but this is not possible currently without breaking the
build because key.h has an implicit include file dependency on
rwsem.h:

    CC [M]  fs/cifs/cifs_spnego.o
  In file included from include/keys/user-type.h:15,
                   from fs/cifs/cifs_spnego.c:24:
  include/linux/key.h:128: error: field ‘sem’ has incomplete type
  make[2]: *** [fs/cifs/cifs_spnego.o] Error 1
  make[1]: *** [fs/cifs] Error 2
  make: *** [fs] Error 2

Fix it by making the dependency explicit.

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237884886.25315.39.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>

Former-commit-id: aa84442d674ef83e1cbf2bce52a20ecff4ce515e