ARM: OMAP2+: Fix board_mux section type conflict when OMAP_MUX is not set
Otherwise we can get:

arch/arm/mach-omap2/mux.h:249:31: error: board_mux causes a section type conflict

Signed-off-by: Tony Lindgren <tony@atomide.com>

Former-commit-id: cc4915d8a0bbe6825eb9fc2c687a0151441af7db