gianfar: Fix build with CONFIG_PM=y
commit 6cb898a0cca6e0f7517d3962d6a6c4aa872f [formerly fba4ed030cfae7efdb6b79a57b0c5a9d72c9] ("gianfar: Add Multiple
Queue Support") introduced the following build failure:

  CC      gianfar.o
gianfar.c: In function 'gfar_restore':
gianfar.c:1249: error: request for member 'napi' in something not a structure or union

This patch fixes the issue.

Signed-off-by: Anton Vorontsov <avorontsov@ru.mvista.com>
Acked-by: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 5ea681d4e6c01b191f01644024f35901721fa438