PCI: label: Fix compilation error when CONFIG_ACPI is unset
This patch fixes compilation error descibed below introduced by
the commit 43f3871274fef0009a009e75b04e981478df6e81 [formerly 6058989bad05b82e78baacce69ec14f27a11b5fd]

drivers/pci/pci-label.c: In function ‘pci_create_firmware_label_files’:
drivers/pci/pci-label.c:366:2: error: implicit declaration of function ‘device_has_dsm’

Signed-off-by: Narendra K <narendra_k@dell.com>
Signed-off-by: Jesse Barnes <jbarnes@virtuousgeek.org>

Former-commit-id: 07eefe1ca542129c24833c96ceb83b9aaa3b458d