Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit b766fe335d26291b5ba28f7ff0504e5eae287cc3 [formerly bc3bf8fd330ce981ce632a1a4a283eee46838f32].

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>

Former-commit-id: 7cbdca23c8a4e6d007b62c9136ba0e5f86e069d0