m32r: build fix for __stringify macro
This patch fixes the following build error of 2.6.30-rc3-git2:

      AS      arch/m32r/kernel/head.o
    In file included from /include/linux/init.h:7,
                     from /arch/m32r/kernel/head.S:11:
    /include/linux/stringify.h:9: error: syntax error in macro parameter list
    /include/linux/stringify.h:10: error: syntax error in macro parameter list

This build error was caused at __HEAD macro in arch/m32r/kernel/head.S,
which uses __stringify() macro.

Remove -traditional option from EXTRA_AFLAGS for the m32r,
because the __stringify() macro depends on the gcc's variadic macro
extension function, due to commit:

    Make __stringify support variable argument macros too
    commit: a1af32e3b15c0ca85928ec97c363299952ec7ac2 [formerly 8f7c2c37319a81ef4c2bfdec67b1ccd5744d97e4]

Signed-off-by: Hirokazu Takata <takata@linux-m32r.org>

Former-commit-id: 9c88b06dc7589fb0bccd617c4659066fb803cfda