sparc,kgdbts: fix compile regression with kgdb test suite
Commit 492a88cf06 [formerly 63ab25ebbc] (kgdbts: unify/generalize gdb breakpoint adjustment)
introduced a compile regression on sparc.

kgdbts.c: In function 'check_and_rewind_pc':
kgdbts.c:307: error: implicit declaration of function 'instruction_pointer_set'

Simply add the correct macro definition for instruction pointer on the
Sparc architecture.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
Acked-by: Mike Frysinger <vapier@gentoo.org>
Acked-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 33d8881af5584fb7994f6b3d17fc11dcaf07b3b2