sh: mach-sdk7786: Fix up fallout from clkdev consolidation.
  CC      arch/sh/boards/mach-sdk7786/setup.o
arch/sh/boards/mach-sdk7786/setup.c:179: error: variable 'sdk7786_pcie_cl' has initializer but incomplete type
arch/sh/boards/mach-sdk7786/setup.c:180: error: unknown field 'con_id' specified in initializer
arch/sh/boards/mach-sdk7786/setup.c:180: warning: excess elements in struct initializer
arch/sh/boards/mach-sdk7786/setup.c:180: warning: (near initialization for 'sdk7786_pcie_cl')
arch/sh/boards/mach-sdk7786/setup.c:181: error: unknown field 'clk' specified in initializer
arch/sh/boards/mach-sdk7786/setup.c:181: warning: excess elements in struct initializer
arch/sh/boards/mach-sdk7786/setup.c:181: warning: (near initialization for 'sdk7786_pcie_cl')
arch/sh/boards/mach-sdk7786/setup.c: In function 'sdk7786_clk_init':
arch/sh/boards/mach-sdk7786/setup.c:211: error: implicit declaration of function 'clkdev_add'

which is a fanciful way of saying that the struct definition moved from
asm/clkdev.h to linux/clkdev.h.

Signed-off-by: Paul Mundt <lethal@linux-sh.org>

Former-commit-id: 3bd75e5e0c5b58636aeadd34890114bcb988777e