FRV: Fix compile breakage
This patch fixes the follwing build error caused by
commit 9cfa1a2dc1bd4aace34e0aec58df704228832719 [formerly 7ca43e7564679604d86e9ed834e7bbcffd8a4a3f]
(mm: use debug_kmap_atomic):

  ...
    AS      arch/frv/mm/tlb-miss.o
  In file included from
  arch/frv/mm/tlb-miss.S:13:
  ...
  Assembler messages:
  include/asm-generic/ioctl.h:73:
  Error: unrecognized instruction `extern unsigned int __invalid_size_argument_for_IO...'
  ...

Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: David Howells <dhowells@redhat.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Former-commit-id: c47ae9adfdd3a9551969534dbb0d5606ec646526