intel_mid_hsi: [REVERT ME] CTP kernel compilation failure if OSPM disabled.
BZ: 30716

This Patch Avoids the compilation failure on CVTP Platform if OSPM is not enabled.
As enable_standby is defined in mfld_pmu file. If OSPM will be disbaledi, mfld-pmu.c file will
compile and enable_stadby will not be defined. And compilation failure will occur.
Error Detail:
drivers/built-in.o: In function `intel_hsi_init':
/home/kratos/android/ics_main/hardware/intel/linux-2.6/drivers/hsi/controllers/intel_mid_hsi.c:
3463:undefined reference to `enable_standby'
make[2]:: *** [.tmp_vmlinux1] Error 1
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory
`/home/kratos/android/ics_main/hardware/intel/linux-2.6'
make: *** [get_kernel_from_source] Error 1
This workaround is Tracked through 28529.

Signed-off-by: Renganathan, Prabu <prabu.renganathan@intel.com>
Signed-off-by: Youvedeep Singh <youvedeep.singh@intel.com>
Change-Id: I71ea506a7b9988922deab6bd93bfcb5d6f1fb882
Reviewed-on: http://android.intel.com:8080/42606
Reviewed-by: Mansoor, Illyas <illyas.mansoor@intel.com>
Tested-by: Seibel, Eric <eric.seibel@intel.com>
Reviewed-by: Cuesta, FernandX <fernandx.cuesta@intel.com>
Tested-by: Cuesta, FernandX <fernandx.cuesta@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

Former-commit-id: d97c8f6557bd95307d980b943263177411b35d33