ARM: 6837/1: remove unused pci_fixup_prpmc1100
The PrPMC1100 machine was removed in 2.6.11, but left a reference to machine_is_prpmc1100 in arch/arm/kernel/bios32.c.  3700cfbe42f91ee8bd7ffbc67cd745b71f162a7b [formerly 6f82f4db80189281a8ac42f2e72396accb719b57] removed the machine type, which causes a build failure:

CC      arch/arm/kernel/bios32.o
arch/arm/kernel/bios32.c: In function 'pci_fixup_prpmc1100':
arch/arm/kernel/bios32.c:174: error: implicit declaration of function 'machine_is_prpmc1100'

Remove the unused pci_fixup_prpcm1100.

Signed-off-by: Colin Cross <ccross@android.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Former-commit-id: 7f479c64a52094354c10309fcacaa71de015dc9e