[media] staging: se401 depends on USB
Fix build errors by adding "depends on USB":

ERROR: "usb_register_driver" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_alloc_urb" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_submit_urb" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_control_msg" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_free_urb" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_kill_urb" [drivers/staging/se401/se401.ko] undefined!
ERROR: "usb_deregister" [drivers/staging/se401/se401.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: ef98a2c0f2856f6b2aa87fd32d5b192afaeae518