m32r: Use generic PREEMPT config
Use the generic preempt config definition in m32r instead of
using a custom one.

This also makes it handle the new CONFIG_PREEMPT_COUNT that
need to be selected by CONFIG_PREEMPT.

Without that it breaks

  kernel/sched.c: In function 'preempt_schedule':
  kernel/sched.c:4364: error: implicit declaration of function 'add_preempt_count_notrace'
  kernel/sched.c:4366: error: implicit declaration of function 'sub_preempt_count_notrace'

Reported-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Frederic Weisbecker <fweisbec@gmail.com>
Cc: Hirokazu Takata <takata@linux-m32r.org>

Former-commit-id: dab16ae1a9fc72a9f419f2dff91854e452d02a5e