kmemleak: fix kconfig for crc32 build error
kmemleak uses crc32 functions so it needs to select CRC32.
Fixes build error:

kmemleak.c:(.text+0x7ce62): undefined reference to `crc32_le'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Former-commit-id: b60e26a2f03d963f8c79ad7920d64abc4d38ecbc