mac8390: Fix build breakage
commit 3a18f1f2922b41d6081880db888e3ae2cd0a2040 [formerly 18c0019102228875cb0f6f252dad5148491e96b2] ("drivers/net/mac8390.c:
Convert printk(KERN_<level> to pr_<level>(") broke the build:

| drivers/net/mac8390.c:306: error: expected ')' before 'version'

as "version" is not a string literal, but a variable.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 51f5300682f5925a11edfddfd47ed47376871974