xen/mmu: Fix compile errors introduced by x86/memblock mismerge.
The git commit 02b66bae4a941d68f51f73df4d98b06d6728352d [formerly d4bbf7e7759afc172e2bfbc5c416324590049cdd]
"Merge branch 'master' into x86/memblock" mismerged the 32-bit
section causing:

arch/x86/xen/mmu.c: In function ‘xen_setup_kernel_pagetable’:
arch/x86/xen/mmu.c:1855: error: expected ‘;’ before ‘)’ token
arch/x86/xen/mmu.c:1855: error: expected statement before ‘)’ token

Acked-by: Tejun Heo <tj@kernel.org>
Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>

Former-commit-id: dc6821e0cfe74802aefd2067b40fcdc03fc4599e