ARM: imx: let MACH_IMX27_VISSTRIM_M10 select IMX_HAVE_PLATFORM_IMX_SSI
mach-imx27_visstrim_m10.c uses imx27_add_imx_ssi() so it needs to select
IMX_HAVE_PLATFORM_IMX_SSI to fix:

	arch/arm/mach-imx/built-in.o: In function `visstrim_m10_board_init':
	mach-imx27_visstrim_m10.c:(.init.text+0x308): undefined reference to `imx_add_imx_ssi'
	mach-imx27_visstrim_m10.c:(.init.text+0x394): undefined reference to `imx27_imx_ssi_data'

Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>

Former-commit-id: 5658bff6c2c4a07fb25195eac70205934b8f5a0d