OMAP: PM: Fix build when CONFIG_PM_DEBUG isn't set
Since a889e1839dd6fb13fa8aa819e9bbf36b45361db8 [formerly 6cdee91257bee23a46dc869ca62469b67cba2c7e] the references to
enable_off_mode and sleep_while_idle can't be resolved when CONFIG_PM_DEBUG
isn't set:
arch/arm/mach-omap2/built-in.o: In function `omap_uart_restore_context':
arch/arm/mach-omap2/serial.c:253: undefined reference to `enable_off_mode'
arch/arm/mach-omap2/built-in.o: In function `omap3_can_sleep':
arch/arm/mach-omap2/pm34xx.c:479: undefined reference to `sleep_while_idle'

Simply #define these in pm.h just like omap2_pm_debug.

Signed-off-by: Loïc Minier <loic.minier@linaro.org>
[khilman: moved down into existing #ifdef section]
Signed-off-by: Kevin Hilman <khilman@deeprootsystems.com>

Former-commit-id: ebfa88cfa1f00022c500e35db63b5f6c977c95c0