msm: fix compile failure on struct membank node member
In commit 9073a12685c93b93b78650af97e1418240538083 [formerly be370302742ff9948f2a42b15cb2ba174d97b930]
"ARM: Remove DISCONTIGMEM support", it removed this "node" member
which cased the following compile failure in mach-msm,

linux/arch/arm/mach-msm/board-halibut.c: In function 'halibut_fixup':
linux/arch/arm/mach-msm/board-halibut.c:86: error: 'struct membank' has no member named 'node'
linux/arch/arm/mach-msm/board-halibut.c:86: error: implicit declaration of function 'PHYS_TO_NID'

I've removed the access to the node member which corrects the
compile failure.

Signed-off-by: Daniel Walker <dwalker@codeaurora.org>

Former-commit-id: 79d98313e0985fa754fc50ea639cbafdfc0860a6