powerbtn: fix the error when compile as a driver module
BZ: 82753

platform_msic_power_btn will not compile as a driver module when
set CONFIG_INTEL_MID_POWER_BUTTON=m, due to undefined reference to
'pb_irq_ack', this patch fixes this issue.

Change-Id: I6e9693c24d84089ca90b62b9031a765b2575e5da
Signed-off-by: Li, Ning <ning.li@intel.com>
Reviewed-on: http://android.intel.com:8080/88828
Reviewed-by: Chen, Jason CJ <jason.cj.chen@intel.com>
Reviewed-by: Yang, Bin <bin.yang@intel.com>
Reviewed-by: Du, Alek <alek.du@intel.com>
Tested-by: Wang, Zhifeng <zhifeng.wang@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

Former-commit-id: efed0c4fa884bac4ded75a3a121162d3a79a8dd2