nilfs: fix breakage caused by barrier flag changes
After merging the block tree, today's linux-next build (powerpc ppc64_defconfig)
failed like this:

fs/nilfs2/the_nilfs.c: In function 'nilfs_discard_segments':
fs/nilfs2/the_nilfs.c:673: error: 'DISCARD_FL_BARRIER' undeclared (first use in this function)

Caused by commit c333f60e737b41e94ab9695b91debd6015ae5d82 [formerly fbd9b09a177a481eda256447c881f014f29034fe] ("blkdev:
generalize flags for blkdev_issue_fn functions") interacting with commit
93f8f5e563fa2274a78893a959f7139626171875 [formerly e902ec9906e844f4613fa6190c6fa65f162dc86e] ("nilfs2: issue discard request
after cleaning segments") (which netered Linus' tree on about March 4 -
before v2.6.34-rc1).

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Jens Axboe <jens.axboe@oracle.com>

Former-commit-id: 6a47dc1418682c83d603b491df1d048f73aa973e