pda_power: Fix build error if !CONFIG_USB_OTG_UTILS
commit 367d82c7d75abfd728c8876e248b97690546c05b [formerly 9ad63986c606c60e2e916b1b96f22991f966d9cc]
"pda_power: Add support for using otg transceiver events"
introduces below build error if !CONFIG_USB_OTG_UTILS.

  CC      drivers/power/pda_power.o
drivers/power/pda_power.c: In function 'pda_power_probe':
drivers/power/pda_power.c:322: error: 'otg_is_usb_online' undeclared (first use in this function)
drivers/power/pda_power.c:322: error: (Each undeclared identifier is reported only once
drivers/power/pda_power.c:322: error: for each function it appears in.)
drivers/power/pda_power.c:325: error: 'otg_is_ac_online' undeclared (first use in this function)
drivers/power/pda_power.c:371: error: 'otg_handle_notification' undeclared (first use in this function)
make[2]: *** [drivers/power/pda_power.o] Error 1
make[1]: *** [drivers/power] Error 2
make: *** [drivers] Error 2

This patch adds #ifdef CONFIG_USB_OTG_UTILS guards at necessary places to fix
build errors.

Signed-off-by: Axel Lin <axel.lin@gmail.com>
Signed-off-by: Anton Vorontsov <cbouatmailru@gmail.com>

Former-commit-id: 1c74529dbecf8839d3ed360690f937d68c14e55b