sh: fix compile error using sh7757lcr_defconfig
Fix the complie error in ehci-hcd.c because it needs an additional
configuration.

  CC      drivers/usb/host/ehci-hcd.o
drivers/usb/host/ehci-hcd.c:1288:2: error: #error "missing bus glue for ehci-hcd"
make[3]: *** [drivers/usb/host/ehci-hcd.o] Error 1
make[2]: *** [drivers/usb/host] Error 2
make[1]: *** [drivers/usb] Error 2
make: *** [drivers] Error 2

Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>

Former-commit-id: bf69d8484cbba2a59dd73cdd20b8d5e79cedce1f