staging: brcm80211: fixed error in non-DHD_DEBUG fullmac build
A build error was introduced with recent fullmac changes when building without
debug option configured:

drivers/staging/brcm80211/brcmfmac/dhd_sdio.c: In function
  ‘dhdsdio_sdiod_drive_strength_init’:
drivers/staging/brcm80211/brcmfmac/dhd_sdio.c:6366:3: error: ‘chn’ undeclared

Cc: devel@linuxdriverproject.org
Cc: linux-wireless@vger.kernel.org
Cc: Brett Rudley <brudley@broadcom.com>
Cc: Henry Ptasinski <henryp@broadcom.com>
Cc: Roland Vossen <rvossen@broadcom.com>
Signed-off-by: Arend van Spriel <arend@broadcom.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: 745492c254c8cd202632c3f8f92a896c5037e249