net: fix typo in drivers/net/ethernet/xilinx/ll_temac_main.c
Commit 0a4a56a34176 [formerly 9e903e085262] ("net: add skb frag size accessors") used frag_size
instead of skb_frag_size in this file.

Fixes this build error:

drivers/net/ethernet/xilinx/ll_temac_main.c: In function 'temac_start_xmit':
drivers/net/ethernet/xilinx/ll_temac_main.c:717:3: error: implicit declaration of function 'frag_size' [-Werror=implicit-function-declaration]

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 2edcd4ca43df3c1d1d392753531cc73a53e709ba