cris: fix the prototype of sync_serial_ioctl()
commit 85975b48db3d6b2629b1e1032fa889404b6386a1 [formerly b4bc281266e84e9a432b588ebdcef5fb94dc8ecb] upstream.

Fix:

  arch/cris/arch-v10/drivers/sync_serial.c:961: error: conflicting types for 'sync_serial_ioctl'

Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: WANG Cong <xiyou.wangcong@gmail.com>
Cc: Mikael Starvik <starvik@axis.com>
Cc: Jesper Nilsson <jesper.nilsson@axis.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>



Former-commit-id: 8ab2e3a2ae06bdd02b2a7269ef6ed896540a6170