staging: brcm80211: fix checkpatch errors in brcmsmac driver
Several source files in brcmsmac driver have checkpatch errors that
have been removed (see below).

ERROR: spaces required around that ':' (ctx:VxV)
+           (u8)NPHY_RSSI_SEL_TSSI_5G:(u8)NPHY_RSSI_SEL_TSSI_2G;
--
ERROR: code indent should use tabs where possible
+ ^Ierr = initvars_table(base, vp, vars, count);$
--

Signed-off-by: Arend van Spriel <arend@broadcom.com>
Reviewed-by: Roland Vossen <rvossen@broadcom.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: 73d924bfe384af21b67f25698bde925f9b02e795