fix leds-intel-kpd.c compile failure when hwmon is set to M
BZ: 82743

leds-intel-kpd.c calls intel_mid_pwm() API, when hwmon is set to M,
there will be undefined reference to `intel_mid_pwm' error.

Make the leds-intel-kpd.c depends on MID_PWM, and export intel_mid_pwm
symbol.

Change-Id: Id329cbab195b64cfdc3bd97d48414d2574c5f7f0
Signed-off-by: Li, Ning <ning.li@intel.com>
Reviewed-on: http://android.intel.com:8080/88852
Reviewed-by: Chen, Jason CJ <jason.cj.chen@intel.com>
Reviewed-by: Yang, Bin <bin.yang@intel.com>
Reviewed-by: Du, Alek <alek.du@intel.com>
Reviewed-by: Koskinen, Ilkka <ilkka.koskinen@intel.com>
Tested-by: Wang, Zhifeng <zhifeng.wang@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

Former-commit-id: 8a3219458856273d6a5159b3e3fee52c5460b31d