atomisp2: append missed include <asm/intel-mid.h>
BZ: 66961

The absence of that header breaks build with

drivers/media/video/atomisp2/atomisp_v4l2.c: In function ‘atomisp_subdev_probe’:
drivers/media/video/atomisp2/atomisp_v4l2.c:501:2: error: implicit declaration of function ‘intel_get_v4l2_subdev_table’ [-Werror=implicit-function-declaration]
drivers/media/video/atomisp2/atomisp_v4l2.c:501:8: error: assignment makes pointer from integer without a cast [-Werror]
cc1: all warnings being treated as errors

and similar errors.

Change-Id: I055e1cfc0bfafdd52182bf097b28c582ffac8e15
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>
Reviewed-on: http://android.intel.com:8080/76120
Reviewed-by: Ailus, Sakari <sakari.ailus@intel.com>
Tested-by: Lampila, KalleX <kallex.lampila@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>

Former-commit-id: 26759c9d5ea236248a8929c75b3b4ece664bfcfd