Revert "TPM: ACPI/PNP dependency removal"
This reverts commit 99090467bc84f55bfbbd5b79530d66792acff2f9 [formerly b89e66e1e396f7b5436af154e58209320cc08aed].

> > When CONFIG_PM is not set:
> >
> > drivers/built-in.o: In function `acpi_init':
> > bus.c:(.init.text+0x2d84): undefined reference to `pm_flags'
> > bus.c:(.init.text+0x2d91): undefined reference to `pm_flags'
>
> CONFIG_ACPI depends on CONFIG_PM,
> so acpi/bus.c should not be compiled for CONFIG_PM=n
>
> Hmm, is is somebody doing something strange, like "select ACPI"
> without guaranteeing that all of ACPI's dependencies are satisfied?

Signed-off-by: James Morris <jmorris@namei.org>

Former-commit-id: ec4a162af388a2716c5314c4aff7029071d09f57