[media] staging: usbvideo/vicam depends on USB
Fix build errors by adding "depends on USB":

ERROR: "usb_register_driver" [drivers/staging/usbvideo/vicam.ko] undefined!
ERROR: "usb_bulk_msg" [drivers/staging/usbvideo/vicam.ko] undefined!
ERROR: "usb_control_msg" [drivers/staging/usbvideo/vicam.ko] undefined!
ERROR: "usb_deregister" [drivers/staging/usbvideo/vicam.ko] undefined!
ERROR: "usb_get_dev" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_put_dev" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_free_urb" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_submit_urb" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_set_interface" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_kill_urb" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_register_driver" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_deregister" [drivers/staging/usbvideo/usbvideo.ko] undefined!
ERROR: "usb_alloc_urb" [drivers/staging/usbvideo/usbvideo.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: 798cf3144f8b7466533cf738740478e472677a01