ARM: 5857/1: ARM: dmabounce: fix build
Commit 47b7dbbcb9e43188bc09cd34d6a39ec58c9602e9 [formerly f74f7e57ae9fa12b2951ae62ce3557799b318399] (ARM: use
flush_kernel_dcache_area() for dmabounce) has broken dmabounce build:

  CC      arch/arm/common/dmabounce.o
arch/arm/common/dmabounce.c: In function 'unmap_single':
arch/arm/common/dmabounce.c:315: error: implicit declaration of function '__cpuc_flush_kernel_dcache_area'
make[2]: *** [arch/arm/common/dmabounce.o] Error 1

Fix it.

Signed-off-by: Mike Rapoport <mike@compulab.co.il>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Former-commit-id: d9fd3ab89ff58ca70c8cc0eadc87cd4a96950f95