ASoC: Fix build error in twl4030.c
Fix the (likely cut-n-paste) error by commit
63d6d33a6e02dd373c44d1c2885d3482d9fbbd94 [formerly 16a30fbb0d3aa4ee829a2dd3d0e314e2b5ae96a9], which causes the error below:
  sound/soc/codecs/twl4030.c: In function 'twl4030_read_reg_cache':
  sound/soc/codecs/twl4030.c:152: error: 'cache' undeclared (first use in this function)

Signed-off-by: Takashi Iwai <tiwai@suse.de>

Former-commit-id: d08664fdb50795b29cf70b0269ea02f7248e76c3