mfd: Fix aat2870 build failure for x86_64
Without this fix, we get:

error: call to ‘copy_from_user_overflow’ declared with attribute error:
copy_from_user() buffer size is not provably correct
make[3]: *** [drivers/mfd/aat2870-core.o] Error 1

And this was triggered by commit da417bacc9143b934f1a480a25d0fb2bb648a820

Signed-off-by: Jin Park <jinyoungp@nvidia.com>
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

Former-commit-id: c38d66ac924e84ea3606c408b117157415df07b3