staging: hv: hv_utils depends on CONNECTOR
Don't build hv_utils when CONFIG_CONNECTOR is not enabled.
Fixes these build errors:

ERROR: "cn_add_callback" [drivers/staging/hv/hv_utils.ko] undefined!
ERROR: "cn_del_callback" [drivers/staging/hv/hv_utils.ko] undefined!
ERROR: "cn_netlink_send" [drivers/staging/hv/hv_utils.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Greg Kroah-Hartman <gregkh@suse.de>
Cc: Hank Janssen <hjanssen@microsoft.com>
Cc: Haiyang Zhang <haiyangz@microsoft.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>

Former-commit-id: 88c8a4437b061dd9dae738802a9eddc297a96278