watchdog: booke_wdt: fix build - unconstify watchdog_info
commit f23fae5df9c19d2c2723f649a31dc5fd2a3c0580 [formerly 42747d712de56cf2087b702d2ad90af114c53138] ("[WATCHDOG] watchdog_info
constify") introduced the following build failure:

   CC      booke_wdt.o
 booke_wdt.c: In function 'booke_wdt_init':
 booke_wdt.c:220: error: assignment of read-only variable 'ident'

Fix this by removing 'const' qualifier from watchdog_info struct.

Signed-off-by: Anton Vorontsov <avorontsov@mvista.com>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Cc: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>



Former-commit-id: d8d8b63b6dc413696ade040e52173c068df11702