xen/xenbus: Fix compile error - missing header for xen_initial_domain()
drivers/xen/xenbus/xenbus_dev_backend.c:74:2: error: implicit declaration of function 'xen_initial_domain'

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>

Former-commit-id: 01464a60a4d21fb649e088f7ae5136c6fb130889