Staging: comedi: uses udelay, needs delay.h
comedi driver(s) use udelay() so they need to #include delay.h.

drivers/staging/comedi/drivers/adq12b.c: In function 'adq12b_ai_rinsn':
drivers/staging/comedi/drivers/adq12b.c:328: error: implicit declaration of function 'udelay'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>



Former-commit-id: f9c51375644e39f9626a4be4101e22d4841980a8