[IA64] Fix build error: conflicting types for ‘sys_execve’
arch/ia64/kernel/process.c:636: error: conflicting types for ‘sys_execve’

commit 16c6895b0391365ba3b34207389466601c865eb2 [formerly d7627467b7a8dd6944885290a03a07ceb28c10eb]
Make do_execve() take a const filename pointer

Missed the declaration of sys_execve in the ia64 asm/unistd.h (perhaps
because there is no reason for it to be there ... it might be a left over
from the COMPAT code?). Just delete the conflicting version.

Signed-off-by: Tony Luck <tony.luck@intel.com>

Former-commit-id: 145e5aa269d54e4ea53fdb5e597007bd287fbe49