powerpc: fix up for mmu_mapin_ram api change
Today's linux-next build (powerpc ppc44x_defconfig) failed like this:

arch/powerpc/mm/pgtable_32.c: In function 'mapin_ram':
arch/powerpc/mm/pgtable_32.c:318: error: too many arguments to function 'mmu_mapin_ram'

Casued by commit 6f0456477cd85e466b354feaa5db45e744a1dc7d [formerly de32400dd26e743c5d500aa42d8d6818b79edb73] ("wii: use both
mem1 and mem2 as ram").

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Grant Likely <grant.likely@secretlab.ca>

Former-commit-id: ae4cec4736969ec2196a6bbce4ab263ff7cb7eef