sound: fix opti92x-ad1848 build
Fix 'else' placement in ifdef block so that build succeeds:

sound/isa/opti9xx/opti92x-ad1848.c:221: error: 'else' without a previous 'if'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

Former-commit-id: 89c0ac7cab2440a771ba1e2ab953186bc9c29786