Input: zylonite-wm97xx - replace IRQ_GPIO() with gpio_to_irq()
Since commit 6384fd "ARM: pxa: rename IRQ_GPIO to PXA_GPIO_TO_IRQ",
I got below buid errors due to implicit declaration of function 'IRQ_GPIO'.

Use common gpio_to_irq() to replace machine dependant macro IRQ_GPIO().

  CC      drivers/input/touchscreen/zylonite-wm97xx.o
drivers/input/touchscreen/zylonite-wm97xx.c: In function 'zylonite_wm97xx_probe':
drivers/input/touchscreen/zylonite-wm97xx.c:195: error: implicit declaration of function 'IRQ_GPIO'
make[3]: *** [drivers/input/touchscreen/zylonite-wm97xx.o] Error 1
make[2]: *** [drivers/input/touchscreen] Error 2
make[1]: *** [drivers/input] Error 2
make: *** [drivers] Error 2

Cc: Mark Brown <broonie@opensource.wolfsonmicro.com>
Cc: Haojian Zhuang <haojian.zhuang@marvell.com>
Signed-off-by: Axel Lin <axel.lin@gmail.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Former-commit-id: b5d798cc7a221aec50baf496c482280f1b809143