ARM: OMAP2+: Fix build error when only ARCH_OMAP2/3 or 4 is selected
Otherwise we'll get undefined reference to `gic_of_init' or
undefined reference to `omap_intc_of_init'.

This was caused by commit 3490ae472d6351daad4777b7d8bffe010c20cc98 [formerly fbf75da733e82bb17a01e1b907b0e40d9c028823]
(ARM: OMAP2+: board-generic: Use of_irq_init API).

Signed-off-by: Tony Lindgren <tony@atomide.com>

Former-commit-id: 75a57fe9cb77e3d3062127cb72d18314f00674d1