perf: hw_breakpoints: Fix percpu namespace clash
Today's linux-next build failed with:

  kernel/hw_breakpoint.c:86: error: 'task_bp_pinned' redeclared as different kind of symbol
  ...

Caused by commit 06d74d1601720739567c6468b1d71165764ce338 [formerly dd17c8f72993f9461e9c19250e3f155d6d99df22] ("percpu:
remove per_cpu__ prefix") from the percpu tree interacting with
commit 7480674d834bbd76fea72ad066a9818df4fb01a7 [formerly 56053170ea2a2c0dc17420e9b94aa3ca51d80408] ("hw-breakpoints:
Fix task-bound breakpoint slot allocation") from the tip tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Acked-by: Frederic Weisbecker <fweisbec@gmail.com>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Tejun Heo <tj@kernel.org>
Cc: Rusty Russell <rusty@rustcorp.com.au>
Cc: Christoph Lameter <cl@linux-foundation.org>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
LKML-Reference: <20091208182515.bb6dda4a.sfr@canb.auug.org.au>
Signed-off-by: Ingo Molnar <mingo@elte.hu>

Former-commit-id: 6ab8886326a1b9a3a8d164d8174e3c20703a03a2