net: fix protocol sk_buff field
Commit b46efd382aa9b [formerly e992cd9b72a18] (kmemcheck: make bitfield annotations truly no-ops
when disabled) allows us to revert a workaround we did in the past to
not add holes in sk_buff structure.

This patch partially reverts commit e4d3b8830aea9 [formerly 14d18a81b5171]
(net: fix kmemcheck annotations) so that sparse doesnt complain:

include/linux/skbuff.h:357:41: error: invalid bitfield specifier for
type restricted __be16.

Reported-by: Stefan Richter <stefanr@s5r6.in-berlin.de>
Signed-off-by: Eric Dumazet <eric.dumazet@gmail.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

Former-commit-id: 4ab408dea0f0dba4dec0555f4f35b7ae703f5e91