MIPS: JZ4740: Fix GCC 4.6.0 build error.
  CC      arch/mips/jz4740/dma.o
arch/mips/jz4740/dma.c: In function 'jz4740_dma_chan_irq':
arch/mips/jz4740/dma.c:245:11: error: variable 'status' set but not used [-Werro
r=unused-but-set-variable]

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

Former-commit-id: f1b6a5054c5c5c1770863b781de9b721fc99c3e3