V4L/DVB (10830): dm1105: uses ir_* functions, select VIDEO_IR
dm1105 uses the ir_*() functions, so it needs to select VIDEO_IR
to avoid build errors:

dm1105.c:(.text+0x26b7ac): undefined reference to `ir_input_keydown'
dm1105.c:(.text+0x26b7bc): undefined reference to `ir_input_nokey'
(.devinit.text+0x29982): undefined reference to `ir_codes_dm1105_nec'
(.devinit.text+0x2998a): undefined reference to `ir_input_init'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>

Former-commit-id: 3341cc6e86da7b956084d5b6c9ca2e4f1c27f9bf