xen/balloon: Move the registration from device to subsystem.
With git commit 1a189a9ee797b00fb15479c76f1f440b4e5b67b4 [formerly 070680218379e15c1901f4bf21b98e3cbf12b527]
"xen-balloon: convert sysdev_class to a regular subsystem" we would
end up with the attributes being put in:

 /sys/devices/xen_memory0/target_kb
instead of
/sys/devices/system/xen_memory/xen_memory0/target_kb

Making the tools inable to deflate the kernel to make more space
for launching another guest and printing:
Error: Failed to query current memory allocation of dom0

Reported-by: Sander Eikelenboom <linux@eikelenboom.it>
Suggested-by:  Kay Sievers <kay.sievers@vrfy.org>
Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>

Former-commit-id: 8ea11f7f11c811d1f502c2dabc5259d447c2f2a0