sh: asm/tlb.h needs linux/swap.h
Commit a38f11d0896285bb4371a892da9f07ebc1d1d843 [formerly 1e56a56410bb64bce62d44563e35a143fc2d515f] introduced the mmu_gather
rework for sh, but missed a linux/swap.h include:

	CC      arch/sh/mm/tlb-urb.o
	In file included from arch/sh/mm/tlb-urb.c:14:0:
	arch/sh/include/asm/tlb.h: In function '__tlb_remove_page':
	arch/sh/include/asm/tlb.h:92:2: error: implicit declaration of function 'free_page_and_swap_cache'

Signed-off-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.yj@renesas.com>
CC: Peter Zijlstra <a.p.zijlstra@chello.nl>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>

Former-commit-id: 194cd8dfc9e4f29249b3bd45c5cb5c0a33a6438c