ARM: CSR: fix build error due to new mdesc->dma_zone_size
commit bc0219ddba2726 [formerly 98b0124f0e2b88]
"ARM: mach-prima2: move ARM_DMA_ZONE_SIZE to mdesc->dma_zone_size"
causes building error:
arch/arm/mach-prima2/prima2.c:39:19: error: 'SZ_256M' undeclared here
(not in a function)

Signed-off-by: Barry Song <baohua.song@csr.com>

Former-commit-id: 1bdfd27a0bd65ccdd7294c1080bdb59f6a5a6e72