elfcore.h : Fix UML build breakage
Commit 74578af645a907ce46cceba97955f14018ec48e1 [formerly a65e7bfcd74e4c0939f235d2bf9f48ddb3a57991] broke the UML build with
the following error -

  In file included from fs/proc/kcore.c:17:
  include/linux/elfcore.h: In function 'elf_core_copy_task_regs':
  include/linux/elfcore.h:129: error: implicit declaration of function 'task_pt_regs'

Fix this by restoring the previous behavior of returning 0 for all arches
like UML that don't define task_pt_regs.

Signed-off-by: Parag Warudkar <parag.lkml@gmail.com>
Acked-by: Amerigo Wang <xiyou.wangcong@gmail.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Former-commit-id: e9bf0cc7cbfbf3952cdf8028aa0d348d09ecdba1