ARM: mini2440: Fix Kconfig to allow kernel to build
The MACH_MINI2440 entry requires the backlight LED driver, but this
subsystem has not been enabled and the select of LEDS_TRIGGER_BACKLIGHT
alone is insufficient to enable the necessary bits of the LED driver.

Add NEW_LEDS, LEDS_CLASS and LEDS_TRIGGER to the select to allow the
kernel to link.

This fixes the following error:

drivers/built-in.o: In function `led_trigger_set':
/home/ben/linux.git/drivers/leds/led-triggers.c:116: undefined reference to `led_brightness_set'

Signed-off-by: Ben Dooks <ben-linux@fluff.org>

Former-commit-id: 2e18edf75d586d9044c1f1e6b1bc8e7c26c4149f