video: nuc900fb: remove include of mach/clkdev.h
Since commit 3b7b74d0e00f3b8e3723d811cde65d35929579af [formerly aa3831cf9d29cfeaebd8c2169378b74111364487]
"ARM: Consolidate the clkdev header files",
the header file arch/arm/mach-nuc93x/include/mach/clkdev.h is removed.

This patch fixes below build error:

drivers/video/nuc900fb.c:42:25: error: mach/clkdev.h: No such file or directory
make[2]: *** [drivers/video/nuc900fb.o] Error 1
make[1]: *** [drivers/video] Error 2
make: *** [drivers] Error 2

Signed-off-by: Axel Lin <axel.lin@gmail.com>
Signed-off-by: Florian Tobias Schandinat <FlorianSchandinat@gmx.de>

Former-commit-id: f88a91ccc8c341e6058c017823e2db266f374024